[package]
name = "create_nft"
version = "1.0.0"
authors = []

[addresses]
owner = "0xd2fc117d7afa1ebafc4af80abb6fc9315f1d497be96ac8d906203459c85285c9"
mint_nft = "0xd2fc117d7afa1ebafc4af80abb6fc9315f1d497be96ac8d906203459c85285c9"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]
